Big refactor for co. Specifically finds one Arctis, and one lineout otherwise fails.  Created a die and a findDevices methods to do the grep and sed to pull indexes.  Will default to the stereo version for Arctis if it can.

diff --git a/bin/co b/bin/co
--- a/bin/co
+++ b/bin/co
@@ -24,8 +24,8 @@
 
 # Set up Debugging flags and function to print variables. {{{1
 [[ $1 == "-D" ]] && let DEBUG=0
-[[ $DEBUG ]] && shift && echo -e "${GREEN}app flag: ${YELLOW}$1${NC}"
 [[ $DEBUG ]] && echo -e "${GREEN}::: DEBUGGING MODE :::${NC}"
+[[ $DEBUG ]] && shift && echo -e "${GREEN}app flag: ${YELLOW}$1${NC}"
 
 debug() {
     # Debug method to print variables more easily
@@ -39,27 +39,65 @@ debug() {
     fi
 } # }}}1
 
+# Helper Functions {{{1
+die() {
+    [[ $DEBUG ]] && echo -e "${RED}ERROR: $PROGRAM:${NC} Line $BASH_LINENO: $*" >&2
+    exit 1
+}
+
+available_sinks=`pacmd list-sinks`
+findDevice() {
+    #[[ ! -z $2 ]] && second="-e $2"
+    echo "$available_sinks" | grep -B 1 -e "$1" \
+        | sed -n -e 's/\index:[[:space:]]\([[:digit:]]\)/\1/p'
+}
+# }}}1
+
 # Progam Begins here.
 # Find the indexes of the output devices {{{
-# Grab the output indexes I want to use. My headphones and stereo.
-arctis="SteelSeries_Arctis_Pro_Wireless-00.stereo-game"
+# Start by defining a regex to find the device by name.
+arctis_stereo="SteelSeries_Arctis_Pro_Wireless-00.stereo-game"
+arctis_mono="SteelSeries_Arctis_Pro_Wireless-00.mono-chat"
 lineout="analog-surround-[[:digit:]]\{2\}" # AKA 'line out'
 lineout2="pci-0000_28_00.3.analog-stereo" # gnome and cinammon had different names. <- was the gnome version
-my_output_devices=`pacmd list-sinks | grep -B 1 -e "$arctis" -e "$lineout" -e "$lineout2" \
-    | sed -n -e 's/\index:[[:space:]]\([[:digit:]]\)/\1/p'`
+
+# Find each device.
+my_output_arctis_stereo=`findDevice "$arctis_stereo"`
+my_output_arctis_mono=`findDevice "$arctis_mono"`
+my_output_lineout=`findDevice "$lineout"`
+[[ -z "$my_output_lineout" ]] && my_output_lineout=`findDevice $lineout2`
+
+# Make sure we found a lineout device.
+[[ -z "$my_output_lineout" ]] && die "No lineout device found."
+
+# Get the arctis stereo output if available, otherwise use the mono
+# Add one arctis device and the lineout device so only 2 outputs are in my_output_devices
+[[ ! -z "$my_output_arctis_stereo" ]] && my_output_arctis="$my_output_arctis_stereo"
+[[ -z "$my_output_arctis" ]] && [[ ! -z "$my_output_arctis_mono" ]] && my_output_arctis="$my_output_arctis_mono"
+[[ -z "$my_output_arctis" ]] && die "No device found for Arctis Pro Wireless Headset"
+my_output_devices=`echo -e "$my_output_arctis\n$my_output_lineout"`
 
 # Get index of device not currently being used, and remove leading whitespace.
 next_out=$(echo "$my_output_devices" | grep -v \* | head -n 1 | sed 's/^ *//g')
 current_default=$(echo "$my_output_devices" | grep \* | sed 's/^ *\*[[:space:]]//g')
 
-# Debug the variables.
+# Debug the variables used so far.
 debug DEBUG $DEBUG
-debug arctis "$arctis"
+debug arctis_stereo "$arctis_stereo"
+debug arctis_mono "$arctis_mono"
 debug linout "$lineout"
 debug linout2 "$lineout2"
+debug my_output_arctis_stereo "$my_output_arctis_stereo"
+debug my_output_arctis_mono "$my_output_arctis_mono"
+debug my_output_arctis "$my_output_arctis"
+debug my_output_lineout "$my_output_lineout"
 debug -n "my_output_devices" "$my_output_devices"
 debug next_out "$next_out"
 debug current_default "$current_default"
+
+# Quick check to see we have 2 devices.
+# TODO: Could probably be removed now.
+[[ $(echo -e "$my_output_devices" | wc -l) < 2 ]] && die "not enough devices found"
 
 # notification flags and icon
 notif_flags="-t 1000 -i $HOME/shared_drive/Pictures/Me/Matt-and-I-Ren-Fair.jpg"
@@ -100,6 +138,10 @@ then
     # Send notification of audio switch
     applicationName=$(echo "$appInfo" | sed -n -e 's/.*application.name[[:space:]]=[[:space:]]"\(.*\)"/\1/p' | head -n 1)
     outputDeviceName=$(pacmd list-sinks | grep -A 65 "index: $next_out" | sed -n -e 's/.*active[[:space:]]port:[[:space:]]<\(.*\)>/\1/p')
+
+    debug apllicationName "$apllicationName"
+    debug outputDeviceName "$outputDeviceName"
+
     notify-send $notif_flags "$notif_title" "$applicationName => $outputDeviceName"
 
     exit 0
@@ -117,6 +159,7 @@ done
 
 # Send notification of audio switch
 outputDeviceName=$(pacmd list-sinks | grep -A 65 "index: $next_out" | sed -n -e 's/.*active[[:space:]]port:[[:space:]]<\(.*\)>/\1/p')
+debug outputDeviceName "$outputDeviceName"
 notify-send $notif_flags "$notif_title" "DEFAULT => $outputDeviceName"
 
 # }}}
